name: biatest
description: Test project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.8.1
  easy_localization: ^3.0.1
  flutter_bloc: ^8.1.2
  biatest_domain:
    path: domain

dependency_overrides:
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  #integration_test:
    #sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/locales/